import localFont from 'next/font/local';
import type { Metadata } from 'next';
import './globals.css';

const sweety = localFont({
  src: '../public/fonts/Sweety.ttf',
  variable: '--font-sweety-local',
  display: 'swap',
});

const desire = localFont({
  src: '../public/fonts/Desire.otf',
  variable: '--font-desire-local',
  display: 'swap',
});

const vani = localFont({
  src: '../public/fonts/Vani.ttf',
  variable: '--font-vani-local',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='hu' className='h-full antialiased'>
      <body
        className={`${sweety.variable} ${desire.variable} ${vani.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
